//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.1

pub use super::fridge::Entity as Fridge;
pub use super::fridge_product_join::Entity as FridgeProductJoin;
pub use super::product::Entity as Product;
